### ISSUE TITLE
Issue when editing Prettier's source code

### ISSUE THREAD

**Issue by duailibe** [t9md/atom-mprettier#9]
Hi! Thanks for this, it feels so much better to load atom now after I switched from `prettier-atom` (I also felt it had too many options).

This works wonderfully with several codebases, but I'm not sure why it doesn't (it simply does not format) with Prettier's repo (http://github.com/prettier/prettier - I'm one of the contributors).

I've tried running format -> `clip debug info` -> paste has nothing. I'm not sure what more information I can give you so here's my setup and settings.

Atom 1.23.1 x64 (macOS Sierra 10.12.6)
mprettier 0.6.0

My settings:

![image](https://user-images.githubusercontent.com/1574588/37219956-d357feca-23a3-11e8-9664-5e703a2c2dca.png)
![image](https://user-images.githubusercontent.com/1574588/37219964-d9aeb9bc-23a3-11e8-8411-b5fd9931d799.png)

Let me know how I can help with this :-) I have zero experience with Atom packages but I'm willing to help

**Comment by duailibe** [comment]
@t9md Do you have any idea what happens here?

**Comment by t9md** [comment]
Sorry for not responding.

**Comment by duailibe** [comment]
@t9md No problem, I ended writing my own plugin =)
